### PR TITLE
A patch to use the config value of max_queue_size

### PR DESCRIPTION
**Pull request by dtheodoro**

### CODE REVIEW

**Comment by anatolijd** [comment]
Hi , @dtheodoro , what's the point of this change ?  Besides it, everything else is OK. Would like to see it merged.

```
-    def initialize(name, host, port, queue_size = MAX_QUEUE_SIZE)
+    def initialize(name, host, port, queue_size = nil)
+      if queue_size.nil?
+         queue_size = MAX_QUEUE_SIZE
+      end
```

**Comment by dtheodoro** [comment]
Hi @anatolijd . Without those lines of code it didn't pass trough the automated tests on Travis CI.

**Comment by grepory** [comment]
As far as I know, there is no longer anyone maintaining this project.  I've moved a fork to grepory/wizardvan if you would like to re-open your PR there.

**Comment by dtheodoro** [comment]
Thanks.
Re-opened on grepory/wizardvan

**Pull request closed without merging**
